sonar.projectKey=sysadiya_ci-cd-pipeline-assignment
sonar.organization=sysadiya
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

