- name: Deploy on Localhost
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Stop existing container (if running)
      command: docker stop customer-order-api
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm customer-order-api
      ignore_errors: yes

    - name: Run new container
      command: docker run -d -p 8080:8080 --name customer-order-api customer-order-api

