package com.msc.cloud.customer_order_api.controller;

import com.msc.cloud.customer_order_api.dto.CustomerDTO;
import com.msc.cloud.customer_order_api.service.CustomerService;
import com.msc.cloud.customer_order_api.service.OrderService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;


@ExtendWith(MockitoExtension.class)
class CustomerControllerTest {

    @Mock
    private CustomerService customerService;

    @Mock
    private OrderService orderService;

    @InjectMocks
    private CustomerController customerController;

    // ===================== getAll =====================

/**
 * ============================================================================
 * EXAMPLE 1 – AI OUTPUT ACCEPTED AS-IS
 * ============================================================================
 *
 * AI-GENERATED TESTS:
 * Unit tests for CustomerController were generated by AI and accepted*/

    @Test
    void getAll_returnsCustomers() {
        CustomerDTO first = new CustomerDTO();
        first.setId(1L);
        first.setName("Alice");
        first.setEmail("alice@example.com");

        CustomerDTO second = new CustomerDTO();
        second.setId(2L);
        second.setName("Bob");
        second.setEmail("bob@example.com");

        List<CustomerDTO> expected = List.of(first, second);
        when(customerService.getAll()).thenReturn(expected);

        List<CustomerDTO> result = customerController.getAll();

        assertNotNull(result);
        assertEquals(2, result.size());
        assertEquals(1L, result.get(0).getId());
        verify(customerService).getAll();
    }

    @Test
    void get_returnsCustomerById() {
        CustomerDTO expected = new CustomerDTO();
        expected.setId(5L);
        expected.setName("Jane");
        expected.setEmail("jane@example.com");

        when(customerService.getById(5L)).thenReturn(expected);

        CustomerDTO result = customerController.get(5L);

        assertNotNull(result);
        assertEquals(5L, result.getId());
        verify(customerService).getById(5L);
    }

    // ===================== create =====================


    @Test
    void create_returnsCreatedCustomer() {
        CustomerDTO input = new CustomerDTO();
        input.setName("Carl");
        input.setEmail("carl@example.com");

        CustomerDTO saved = new CustomerDTO();
        saved.setId(10L);
        saved.setName("Carl");
        saved.setEmail("carl@example.com");

        when(customerService.save(input)).thenReturn(saved);

        ResponseEntity<CustomerDTO> response = customerController.create(input);

        assertNotNull(response);
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals(10L, response.getBody().getId());
        verify(customerService).save(input);
    }

    @Test
    void update_setsIdAndReturnsUpdatedCustomer() {
        CustomerDTO input = new CustomerDTO();
        input.setName("Nora");
        input.setEmail("nora@example.com");

        CustomerDTO saved = new CustomerDTO();
        saved.setId(7L);
        saved.setName("Nora");
        saved.setEmail("nora@example.com");

        when(customerService.save(input)).thenReturn(saved);

        CustomerDTO result = customerController.update(7L, input);

        assertNotNull(result);
        assertEquals(7L, result.getId());

        ArgumentCaptor<CustomerDTO> captor = ArgumentCaptor.forClass(CustomerDTO.class);
        verify(customerService).save(captor.capture());
        assertEquals(7L, captor.getValue().getId());
    }

    // ===================== delete =====================


    @Test
    void delete_removesCustomer() {
        ResponseEntity<Void> response = customerController.delete(3L);

        assertNotNull(response);
        assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
        verify(customerService).delete(3L);
    }

    @Test
    void shouldReturnNotFoundWhenCustomerDoesNotExist() {
        // Arrange
        Long customerId = 99L;

        when(customerService.getById(customerId))
                .thenThrow(new RuntimeException("Customer not found"));

        // Act & Assert - getById method throws exception when not found
        try {
            customerController.get(customerId);
        } catch (RuntimeException e) {
            assertEquals("Customer not found", e.getMessage());
        }
        verify(customerService).getById(customerId);
    }

    @Test
    void shouldSaveCustomerWithValidData() {
        // Arrange
        CustomerDTO customerDTO = new CustomerDTO();
        customerDTO.setName("Test");
        customerDTO.setEmail("test@example.com");

        CustomerDTO savedCustomer = new CustomerDTO();
        savedCustomer.setId(1L);
        savedCustomer.setName("Test");
        savedCustomer.setEmail("test@example.com");

        when(customerService.save(customerDTO)).thenReturn(savedCustomer);

        // Act
        ResponseEntity<CustomerDTO> response = customerController.create(customerDTO);

        // Assert
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals(1L, response.getBody().getId());
        verify(customerService).save(customerDTO);
    }
}

