name: CI-CD Pipeline (Local Deployment)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3️⃣ Build & Test
      - name: Build and Test
        run: mvn clean verify

      # 4️⃣ Sonar Analysis
      - name: SonarCloud Analysis
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar \
          -Dsonar.projectKey=sysadiya_ci-cd-pipeline-assignment \
          -Dsonar.organization=sysadiya \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 5️⃣ Build Docker Image
      - name: Build Docker Image
        run: docker build -t customer-order-api .

      # 6️⃣ Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # 7️⃣ Run Ansible (LOCALHOST 🚀)
      - name: Deploy Locally using Ansible
        run: |
          ansible-playbook ansible/deploy.yml
